config/routes.rb
Rails.application.routes.draw do
  resources :router_statuses

  resources :packages

  resources :notification_lists

  resources :routers

  resources :stores

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_one :router
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all()
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @packages = Package.all()
  end


  # GET /stores/new
  def new
    @store = Store.new
    router = @store.build_router
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @router_params = params[:store][:router]
    params[:store].delete(:router)
    @store = Store.new(store_params)
    @store.build_router(@router_params)
    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :location, :address,router: [:name])
    end
    def router_params
      params.require(:router).permit(:name)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.haml
= simple_form_for @store, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = error_span(@store[:name])
  = f.input :location
  = error_span(@store[:location])
  = f.input :address
  = error_span(@store[:address])
  =# render :partial => "router", :object => @router
  = f.fields_for :router do |builder|
    = render "router", :f => builder
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), stores_path, :class => 'btn btn-default'

app/views/stores/_packages.html.haml
- model_class = Package
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:type)
      %th= model_class.human_attribute_name(:created_at)
      %th= model_class.human_attribute_name(:package_url)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @packages.each do |package|
      %tr
        %td= link_to package.id, package_path(package)
        %td= package.name
        %td= package.type
        %td=l package.created_at
        %td= package.avatar_url() if package.avatar?
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_package_path(package), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), package_path(package), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to "Add Packages", packages_path, :class => 'btn btn-primary'

app/views/stores/_router.html.haml
%p
  = f.label :name , "Router Name"
  = f.text_field :name
  = f.label :MacId , "Router Mac Id"
  = f.text_field :macid

app/views/stores/edit.html.haml
- model_class = Store
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stores/index.html.haml
- model_class = Store
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:location)
      %th= model_class.human_attribute_name(:macid)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @stores.each do |store|
      %tr
        %td= link_to store.id, store_path(store)
        %td= store.name
        %td= store.location
        %td= store.address
        %td= store.router.macid
        %td=l store.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_store_path(store), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), store_path(store), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_store_path, :class => 'btn btn-primary'

app/views/stores/new.html.haml
- model_class = Store
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stores/show.html.haml
- model_class = Store
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @store.name
%p
  %strong= model_class.human_attribute_name(:location) + ':'
  %br
  = @store.location
%p
  %strong= model_class.human_attribute_name(:address) + ':'
  %br
  = @store.address
%p
  %strong= model_class.human_attribute_name(:route_id) + ':'
  %br
  = @store.route_id



= link_to t('.back', :default => t("helpers.links.back")), stores_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_store_path(@store), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), store_path(@store), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

= render "packages"