config/routes.rb
Rails.application.routes.draw do
  resources :router_statuses

  resources :packages

  resources :notification_lists

  resources :routers

  resources :stores

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/notification_list.rb
class NotificationList < ActiveRecord::Base
end

app/controllers/notification_lists_controller.rb
class NotificationListsController < ApplicationController
  before_action :set_notification_list, only: [:show, :edit, :update, :destroy]

  # GET /notification_lists
  # GET /notification_lists.json
  def index
    @notification_lists = NotificationList.all
  end

  # GET /notification_lists/1
  # GET /notification_lists/1.json
  def show
  end

  # GET /notification_lists/new
  def new
    @notification_list = NotificationList.new
  end

  # GET /notification_lists/1/edit
  def edit
  end

  # POST /notification_lists
  # POST /notification_lists.json
  def create
    @notification_list = NotificationList.new(notification_list_params)

    respond_to do |format|
      if @notification_list.save
        format.html { redirect_to @notification_list, notice: 'Notification list was successfully created.' }
        format.json { render :show, status: :created, location: @notification_list }
      else
        format.html { render :new }
        format.json { render json: @notification_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notification_lists/1
  # PATCH/PUT /notification_lists/1.json
  def update
    respond_to do |format|
      if @notification_list.update(notification_list_params)
        format.html { redirect_to @notification_list, notice: 'Notification list was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification_list }
      else
        format.html { render :edit }
        format.json { render json: @notification_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notification_lists/1
  # DELETE /notification_lists/1.json
  def destroy
    @notification_list.destroy
    respond_to do |format|
      format.html { redirect_to notification_lists_url, notice: 'Notification list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification_list
      @notification_list = NotificationList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_list_params
      params.require(:notification_list).permit(:name, :email, :phno)
    end
end

app/helpers/notification_lists_helper.rb
module NotificationListsHelper
end

app/views/notification_lists/_form.html.haml
= simple_form_for @notification_list, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = error_span(@notification_list[:name])
  = f.input :email
  = error_span(@notification_list[:email])
  = f.input :phno
  = error_span(@notification_list[:phno])
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), notification_lists_path, :class => 'btn btn-default'

app/views/notification_lists/edit.html.haml
- model_class = NotificationList
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/notification_lists/index.html.haml
- model_class = NotificationList
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:phno)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @notification_lists.each do |notification_list|
      %tr
        %td= link_to notification_list.id, notification_list_path(notification_list)
        %td= notification_list.name
        %td= notification_list.email
        %td= notification_list.phno
        %td=l notification_list.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_notification_list_path(notification_list), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), notification_list_path(notification_list), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_notification_list_path, :class => 'btn btn-primary'

app/views/notification_lists/new.html.haml
- model_class = NotificationList
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/notification_lists/show.html.haml
- model_class = NotificationList
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @notification_list.name
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @notification_list.email
%p
  %strong= model_class.human_attribute_name(:phno) + ':'
  %br
  = @notification_list.phno


= link_to t('.back', :default => t("helpers.links.back")), notification_lists_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_notification_list_path(@notification_list), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), notification_list_path(@notification_list), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'