config/routes.rb
Rails.application.routes.draw do
  resources :router_statuses

  resources :packages

  resources :notification_lists

  resources :routers

  resources :stores

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/controllers/router_statuses_controller.rb
class RouterStatusesController < ApplicationController
  before_action :set_router_status, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:create] ,if: :json_request?

  # GET /router_statuses
  # GET /router_statuses.json
  def index
    @router_statuses = RouterStatus.status_display
  end

  # GET /router_statuses/1
  # GET /router_statuses/1.json
  def show
  end

  # GET /router_statuses/new
  def new
    @router_status = RouterStatus.new
  end

  # GET /router_statuses/1/edit
  def edit
  end

  # POST /router_statuses
  # POST /router_statuses.json
  def create
    @router_status = RouterStatus.new(router_status_params)

    respond_to do |format|
      if @router_status.save
        format.html { redirect_to @router_status, notice: 'Router status was successfully created.' }
        format.json { render :show, status: :created, location: @router_status }
      else
        format.html { render :new }
        format.json { render json: @router_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /router_statuses/1
  # PATCH/PUT /router_statuses/1.json
  def update
    respond_to do |format|
      if @router_status.update(router_status_params)
        format.html { redirect_to @router_status, notice: 'Router status was successfully updated.' }
        format.json { render :show, status: :ok, location: @router_status }
      else
        format.html { render :edit }
        format.json { render json: @router_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /router_statuses/1
  # DELETE /router_statuses/1.json
  def destroy
    @router_status.destroy
    respond_to do |format|
      format.html { redirect_to router_statuses_url, notice: 'Router status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def json_request?
      request.format.json?
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_router_status
      @router_status = RouterStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def router_status_params
      params.require(:router_status).permit(:router_id, :macid, :status)
    end
end

app/helpers/router_statuses_helper.rb
module RouterStatusesHelper
end

app/views/router_statuses/_form.html.haml
= simple_form_for @router_status, :html => { :class => 'form-horizontal' } do |f|
  = f.input :router_id
  = error_span(@router_status[:router_id])
  = f.input :status
  = error_span(@router_status[:status])
  = f.input :time
  = error_span(@router_status[:time])
  = f.input :macid
  = error_span(@router_status[:macid])
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), router_statuses_path, :class => 'btn btn-default'

app/views/router_statuses/edit.html.haml
- model_class = RouterStatus
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/router_statuses/index.html.haml
- model_class = RouterStatus
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:router_id)
      %th= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:time)
      %th= model_class.human_attribute_name(:macid)
      %th= model_class.human_attribute_name(:created_at)
  %tbody
    - @router_statuses.each do |router_status|
      %tr
        %td= link_to router_status.id, router_status_path(router_status)
        %td= router_status.router_id
        - if router_status.status == 0
          %td
            %p.router_down= router_status.status
        - else
          %td
            %p.router_up= router_status.status
        %td= router_status.time
        %td= router_status.macid
        %td=l router_status.created_at
        %td
= link_to t('.new', :default => t("helpers.links.new")), new_router_status_path, :class => 'btn btn-primary'

app/views/router_statuses/new.html.haml
- model_class = RouterStatus
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/router_statuses/show.html.haml
- model_class = RouterStatus
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:router_id) + ':'
  %br
  = @router_status.router_id
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @router_status.status
%p
  %strong= model_class.human_attribute_name(:time) + ':'
  %br
  = @router_status.time
%p
  %strong= model_class.human_attribute_name(:macid) + ':'
  %br
  = @router_status.macid


= link_to t('.back', :default => t("helpers.links.back")), router_statuses_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_router_status_path(@router_status), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), router_status_path(@router_status), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'