config/routes.rb
Rails.application.routes.draw do
  resources :router_statuses

  resources :packages

  resources :notification_lists

  resources :routers

  resources :stores

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/views/layouts/_admin_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <!--<li><%= link_to current_user.name , edit_user_registration_path %></li>-->
  <li><%= link_to 'My Account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'Users', users_path %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <% if current_user.admin? %>
                <%= render 'layouts/admin_navigation_links' %>
            <% else %>
                <%= render 'layouts/user_navigation_links' %>
            <% end %>
        <% else %>
            <%= render 'layouts/user_navigation_links' %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_user_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to 'Home', root_path, class: 'navbar-brand' %>
<% if user_signed_in? %>
  <!--<li><%= link_to current_user.name , edit_user_registration_path %></li>-->
  <!--<li><%= link_to 'My Account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>-->
<% else %>
    <li><%= link_to 'Stores', stores_path %></li>
    <li><%= link_to 'Packages', packages_path %></li>
    <li><%= link_to 'Routers', routers_path %></li>
    <li><%= link_to 'Notification Lists', notification_lists_path %></li>

<!--    <li><%= link_to 'Sign in', new_user_session_path %></li>-->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sangeeta" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
      <div class="col-lg-3">
      </div><!--/span-->
    </div><!--/row-->

    <hr>
    <div class="row">
      <div class="col-xs-12">
        <footer>
          <p>&copy; Copyright 2015 powered by ZipoPay www.zipopay.com</p>
        </footer>
      </div>
    </div>
  </div> <!-- /container -->
  </body>
</html>